### ISSUE TITLE
Remote server returned an error: (409) Conflict

### ISSUE THREAD

**Issue by billziss-gh** [chocolatey/home#243]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

While attempting to push an update to an existing package I am receiving the following error (from the logs):

```
2023-02-24 19:44:36,274 24784 [INFO ] - ============================================================
2023-02-24 19:44:36,352 24784 [INFO ] - Chocolatey v1.2.1
2023-02-24 19:44:36,477 24784 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2023-02-24 19:44:36,508 24784 [INFO ] - Attempting to push winfsp.2.0.23055-pre.nupkg to https://push.chocolatey.org/
2023-02-24 19:44:38,965 24784 [ERROR] - An error has occurred. It's possible the package version already exists on the repository or a nuspec element is invalid. See error below...
2023-02-24 19:44:38,980 24784 [ERROR] - Failed to process request. 'Conflict'. 
The remote server returned an error: (409) Conflict..
2023-02-24 19:44:38,980 24784 [ERROR] - More Details: System.InvalidOperationException: Failed to process request. 'Conflict'. 
The remote server returned an error: (409) Conflict.. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   --- End of inner exception stack trace ---
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at chocolatey.infrastructure.app.nuget.NugetPush.push_package(ChocolateyConfiguration config, String nupkgFilePath)
   at chocolatey.infrastructure.app.services.NugetService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
```

### What is Expected?

I expected that new package to be pushed successfully.

### How Did You Get This To Happen?

I ran the command `choco push winfsp.2.0.23055-pre.nupkg`.

### System Details

* Operating System: Windows 11 22H2
* Windows PowerShell version: 5.1.22621.963
* Chocolatey CLI Version: 1.2.1
* Chocolatey Licensed Extension version: Chocolatey v1.2.1
* Chocolatey License type:
* Terminal/Emulator: Windows Terminal

### Installed Packages

```bash
N/A
```

### Output Log

```bash
2023-02-24 19:44:36,274 24784 [INFO ] - ============================================================
2023-02-24 19:44:36,352 24784 [INFO ] - Chocolatey v1.2.1
2023-02-24 19:44:36,477 24784 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2023-02-24 19:44:36,508 24784 [INFO ] - Attempting to push winfsp.2.0.23055-pre.nupkg to https://push.chocolatey.org/
2023-02-24 19:44:38,965 24784 [ERROR] - An error has occurred. It's possible the package version already exists on the repository or a nuspec element is invalid. See error below...
2023-02-24 19:44:38,980 24784 [ERROR] - Failed to process request. 'Conflict'. 
The remote server returned an error: (409) Conflict..
2023-02-24 19:44:38,980 24784 [ERROR] - More Details: System.InvalidOperationException: Failed to process request. 'Conflict'. 
The remote server returned an error: (409) Conflict.. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   --- End of inner exception stack trace ---
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at chocolatey.infrastructure.app.nuget.NugetPush.push_package(ChocolateyConfiguration config, String nupkgFilePath)
   at chocolatey.infrastructure.app.services.NugetService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
```

### Additional Context

- I have seen issue #105, but do not believe it is related to this. I have checked that my description is less than 4000 long.
- Related nuspec file: https://github.com/winfsp/winfsp/blob/master/build/choco/winfsp.nuspec

**Comment by pauby** [comment]
How many times did you try this? Could be a transient error.

Can you fix your iconUrl as it doesn't meet the requirements?

**Comment by billziss-gh** [comment]
I tried it a few times. I just retried and it worked.
